// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDa6cGrCTZ6fXX-lJMQKjEs0V7plSc995w',
    appId: '1:31725168630:web:4051df77071160503b89d7',
    messagingSenderId: '31725168630',
    projectId: 'blood-app-4556',
    authDomain: 'blood-app-4556.firebaseapp.com',
    storageBucket: 'blood-app-4556.firebasestorage.app',
    measurementId: 'G-92GGN0XH3D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsaQGxKEsiKEz_5gNPW9EUcG6kteHCAmo',
    appId: '1:31725168630:android:7c7c8f3e444923cd3b89d7',
    messagingSenderId: '31725168630',
    projectId: 'blood-app-4556',
    storageBucket: 'blood-app-4556.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgqkX6VQRx5KcixhFGBhVxXvF0Qowf_QQ',
    appId: '1:31725168630:ios:9b61caf44ac2ae223b89d7',
    messagingSenderId: '31725168630',
    projectId: 'blood-app-4556',
    storageBucket: 'blood-app-4556.firebasestorage.app',
    iosBundleId: 'com.microcode.bloodApp',
  );
}
